# Generated by Django 5.2 on 2025-05-06 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="consultas_restantes",
            field=models.IntegerField(default=0),
        ),
    ]
