# Generated by Django 5.2 on 2025-05-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_nombre_completo_user_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="rut",
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
