# Generated by Django 5.2 on 2025-05-07 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_rut"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="rut",
        ),
    ]
