# Generated by Django 5.2 on 2025-05-06 01:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Suscripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "fecha_inicio",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("fecha_expiracion", models.DateTimeField(blank=True, null=True)),
                (
                    "fecha_ultima_renovacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "origen_pago",
                    models.CharField(
                        help_text="Origen del pago (ej: PayPal, transferencia, etc)",
                        max_length=100,
                    ),
                ),
                (
                    "referencia_pago",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Monto de la suscripción",
                        max_digits=10,
                    ),
                ),
                (
                    "moneda",
                    models.CharField(
                        default="USD",
                        help_text="Moneda de la suscripción (USD, EUR, CLP, etc.)",
                        max_length=3,
                    ),
                ),
                ("renovacion_automatica", models.BooleanField(default=True)),
                ("ultima_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistorialPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_pago", models.DateTimeField(default=django.utils.timezone.now)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("moneda", models.CharField(default="USD", max_length=3)),
                (
                    "metodo_pago",
                    models.CharField(
                        help_text="Método de pago utilizado (PayPal, transferencia, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "referencia",
                    models.CharField(
                        blank=True,
                        help_text="Número de referencia o ID de transacción",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("completado", "Completado"),
                            ("fallido", "Fallido"),
                            ("reembolsado", "Reembolsado"),
                        ],
                        default="completado",
                        max_length=20,
                    ),
                ),
                (
                    "notas",
                    models.TextField(
                        blank=True,
                        help_text="Información adicional sobre el pago",
                        null=True,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "suscripcion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos",
                        to="administrador.suscripcion",
                    ),
                ),
            ],
        ),
    ]
