# Generated by Django 5.2 on 2025-05-04 02:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('mensual', 'Mensual con renovación')], default='mensual', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
                ('consultas_restantes', models.IntegerField(default=30)),
                ('perfumes_maximos', models.IntegerField(default=100)),
                ('renovacion_automatica', models.BooleanField(default=True)),
                ('origen_pago', models.CharField(choices=[('paypal', 'PayPal'), ('manual', 'Manual')], default='paypal', max_length=20)),
                ('referencia_pago', models.CharField(blank=True, max_length=100, null=True)),
                ('paypal_subscription_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('paypal_plan_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
