# Generated by Django 5.2 on 2025-05-07 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrador", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="suscripcion",
            name="flow_customer_id",
            field=models.CharField(
                blank=True,
                help_text="ID del cliente en Flow",
                max_length=100,
                null=True,
            ),
        ),
    ]
