# Generated by Django 5.2 on 2025-05-01 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('perfumista', models.CharField(blank=True, max_length=100, null=True)),
                ('concentracion', models.CharField(choices=[('EDT', 'Eau de Toilette'), ('EDP', 'Eau de Parfum'), ('PARFUM', 'Parfum'), ('EXTRAIT', 'Extrait')], max_length=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='perfumes/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
