# Generated by Django 5.2 on 2025-05-02 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfume',
            name='concentracion',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='usuario',
        ),
        migrations.AddField(
            model_name='perfume',
            name='acordes',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='perfume',
            name='notas',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='ColeccionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfumes.perfume')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'perfume')},
            },
        ),
    ]
