# Generated by Django 5.2 on 2025-05-02 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0002_remove_perfume_concentracion_remove_perfume_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='acordes',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='notas',
            field=models.JSONField(),
        ),
    ]
