# Generated by Django 5.2 on 2025-05-01 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfumes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evento', models.DateField()),
                ('hora_evento', models.TimeField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('lugar_tipo', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], max_length=10)),
                ('lugar_descripcion', models.CharField(max_length=150)),
                ('lugar_nombre', models.CharField(max_length=100)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('ocasion', models.CharField(max_length=100)),
                ('expectativa', models.CharField(max_length=100)),
                ('vestimenta', models.CharField(max_length=100)),
                ('clima_descripcion', models.CharField(max_length=100)),
                ('temperatura', models.FloatField()),
                ('humedad', models.FloatField()),
                ('prompt', models.TextField()),
                ('respuesta_ia', models.TextField()),
                ('explicacion', models.TextField(blank=True)),
                ('perfume_recomendado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='perfumes.perfume')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
